### ISSUE TITLE
[reactive_image_picker]  4.0.1 depends on app_settings ^4.2.0

### ISSUE THREAD

**Issue by teusemanuel** [artflutter/reactive_forms_widgets#116]
I would like to thank you, because this set of packages is very good.

The problem I'm facing is to install the reactive_image_picker package without the app_settings package, looking at the code this dependency is only necessary in the example and not in the library itself

**Comment by teusemanuel** [comment]
here is my `pubspec.yaml`
```
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.0

    #core
    rxdart: ^0.27.3
    bloc: ^8.0.1
    flutter_bloc: ^8.0.1
    equatable: ^2.0.3
    json_annotation: ^4.4.0
    intl: ^0.18.0
    shared_preferences: ^2.0.12
    image_picker: ^0.8.7+4
    image_cropper: ^5.0.0

    #forms
    reactive_forms: ^16.0.3
    reactive_flutter_typeahead: ^2.0.0

    #utils
    cpf_cnpj_validator: ^2.0.0
    pdf: ^3.6.5
    barcode_widget: ^2.0.2
    esys_flutter_share_plus: ^2.0.1
    path_provider: ^2.0.8
    url_launcher: ^6.0.18
    package_info_plus: ^4.1.0
    launch_review: ^3.0.1
    connectivity_plus: ^4.0.2
    flutter_facebook_auth: ^6.0.0 #facebook login
    in_app_update: ^4.1.4
    collection: ^1.15.0
    open_file: ^3.0.3
    freezed_annotation: ^2.4.1

    #UX
    animations: ^2.0.2 #TODO create motion animations between pages

    #DI
    injectable: ^2.2.0
    get_it: ^7.6.0

    #UI
    image: ^4.0.17
    shimmer: ^3.0.0
    transparent_image: ^2.0.1

    #Shared Libs
    common_widgets:
      path: packages/common_widgets

    flutter_signature_pad: ^3.0.1
    scrollable_positioned_list: ^0.3.8

    fluttertoast: ^8.0.9
    flutter_pdfview: ^1.2.2

    #http
    dio: ^5.3.1
    fk_user_agent: ^2.1.0
    retrofit: ^4.0.1
    logger: ^2.0.1  #for logging purpose

    #firebase configs
    firebase_core: ^2.15.0
    firebase_core_platform_interface: ^4.8.0
    firebase_analytics: ^10.4.4
    firebase_crashlytics: ^3.3.4
    firebase_messaging: ^14.6.5
    firebase_performance: ^0.9.2+4

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_launcher_icons: ^0.13.1
    freezed: ^2.4.1

    build_runner: ^2.4.6
    json_serializable: ^6.1.1
    injectable_generator: ^2.3.0
    retrofit_generator: ^7.0.8
```

when I add the `reactive_image_picker` lib these dependencies are added

```
Resolving dependencies...
  _fe_analyzer_shared 61.0.0 (64.0.0 available)
  analyzer 5.13.0 (6.2.0 available)
+ app_settings 4.3.1 (5.0.0 available)
  collection 1.17.1 (1.18.0 available)
+ csslib 1.0.0
  file 6.1.4 (7.0.0 available)
  freezed 2.4.1 (2.4.2 available)
+ html 0.15.4
  image_picker 0.8.9 (1.0.2 available)
  image_picker_for_web 2.2.0 (3.0.0 available)
  intl 0.18.0 (0.18.1 available)
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.2.0 (0.8.0 available)
  reactive_forms 16.0.3 (16.0.4 available)
+ reactive_image_picker 4.0.1
  shared_preferences_foundation 2.3.2 (2.3.3 available)
  source_span 1.9.1 (1.10.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test_api 0.5.1 (0.6.1 available)
+ video_player 2.7.0
+ video_player_android 2.4.9
+ video_player_avfoundation 2.4.9
+ video_player_platform_interface 6.2.0
+ video_player_web 2.0.16
Changed 9 dependencies!
exit code 0
```

up to this point there is no problem, but when I start the app in the IOS emulator, I get this error in the pods

![Screenshot 2023-08-15 at 10 16 25](https://github.com/artflutter/reactive_forms_widgets/assets/15304114/a351b9df-803c-433b-a4a7-351f6215dc79)
